### PR TITLE
Feature request: Add Ruby-specific tools

### PR DESCRIPTION
**Pull request by dazuma**
A module containing common Ruby-specific tools that we are using across multiple synth scripts. Currently there is a merge function (see #21) for gemspec files, and a procedure for deleting a specific named Ruby method out of a file (which we use regularly for partial gapics).

I haven't yet been able to get nox to work locally, so there might be lint issues...

### CODE REVIEW

**Comment by theacodes** [comment]
I'd love to see tests for this at some point. Let's see if Kokoro passes lint and stuff.

**Comment by dazuma** [comment]
I modified updated the merge_gemspec method to match what we eventually ended up using in the ruby synth scripts.

**Comment by theacodes** [comment]
Seems lint is failing, can you run `nox -s blacken` to fix?

**Comment by dazuma** [comment]
I haven't been able to get nox to work. I get this:

```
Traceback (most recent call last):
  File "/usr/local/google/home/dazuma/opt/asdf/installs/python/3.6.5/bin/nox", line 7, in <module>
    from nox.main import main
  File "/usr/local/google/home/dazuma/src/github/synthtool/nox.py", line 18, in <module>
    @nox.session(python='3.6')
AttributeError: module 'nox' has no attribute 'session'
```

**Comment by theacodes** [comment]
very weird. We'll need to figure that out at some point.

**Comment by kinwa91** [comment]
> I haven't been able to get nox to work. I get this:

Same here.

**Pull request merged**
