### PR TITLE
Run `npm install` verbose

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
FYI @soldair

**Comment by soldair** [comment]
could we try to replace `npm install --verbose` with 
`npx gist:45d18dfcca291e019ef420af7831f96c 10000 2 install`?

**Comment by alexander-fenster** [comment]
Can we try in one repo first?  Go ahead and add it here https://github.com/googleapis/nodejs-kms/tree/npm-verbose just to verify it works, then I think we're good to go.

**Comment by alexander-fenster** [comment]
Actually I will just try :)

**Pull request closed without merging**
